version: '3.8'

services:

  localstack:
    hostname: localstack
    image: localstack/localstack:1.4
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - INIT_SCRIPTS_PATH=/tmp/localstack/scripts
    ports:
      - '4566:4566'
    healthcheck:
      test: curl --fail http://localhost:4566/_localstack/health
      interval: 10s
      retries: 5
    volumes:
      - "./.localstack/scripts/:/etc/localstack/init/ready.d/"
      - "./.localstack/scripts/resources/:/tmp/lambda"
      - "/var/run/docker.sock:/var/run/docker.sock"