version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: chambeo_postgres
    environment:
      POSTGRES_USER: chambeo
      POSTGRES_PASSWORD: chambeo
      POSTGRES_DB: chambeo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
